# Generated by Django 4.0.2 on 2022-02-19 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_discount_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='lug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='lug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
