# Generated by Django 4.0.2 on 2022-02-19 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_lug_productcategory_lug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='lug',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='productcategory',
            old_name='lug',
            new_name='slug',
        ),
    ]
